import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";



const myFontOne = localFont({src : "../../public/fonts/fontOne.otf"})



export const metadata: Metadata = {
  title: "TeachAI",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${myFontOne.className} bg-gradient-to-b from-indigo-50 to-white`}
      >
        {children}
      </body>
    </html>
  );
}
